--------------------------------------------------------
--  File created - воскресенье-апреля-24-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SUPPLIERS_OF_PRODUCTS
--------------------------------------------------------

  CREATE TABLE "STORE"."SUPPLIERS_OF_PRODUCTS" 
   (	"SUPPLIER_ID" NUMBER, 
	"ORGANIZATION_NAME" VARCHAR2(100 BYTE), 
	"PERSON_IN_CHARGE" VARCHAR2(100 BYTE), 
	"ADRESS" VARCHAR2(12 BYTE), 
	"PHONE_NUMBER" NUMBER, 
	"EMAIL" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007085
--------------------------------------------------------

  CREATE UNIQUE INDEX "STORE"."SYS_C007085" ON "STORE"."SUPPLIERS_OF_PRODUCTS" ("SUPPLIER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SUPPLIERS_OF_PRODUCTS
--------------------------------------------------------

  ALTER TABLE "STORE"."SUPPLIERS_OF_PRODUCTS" ADD PRIMARY KEY ("SUPPLIER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
